public with sharing class AccountContactInsert {
	/*
	public static void InsertContact(Account acc){
		Contact c = new Contact();
		c.AccountId = acc.Id;
		c.LastName = acc.Name;
		
		insert c;
	}
	*/
	/*
	public static void InsertContact(List<Account> acc){
		
		List<Contact> conList = new List<Contact>();
		
		for (Account a: acc){
			
			conList.add(new Contact(AccountId = a.Id, lastname = a.Name));
		}	
		if (conList.size() > 0){
			insert conList;
		}
	}
	
	static testMethod void myTest() {
		
	}*/
}